### ISSUE TITLE
Error: Unable to retrieve the password!

### ISSUE THREAD

**Issue by networkexpress** [PBujakiewicz/KeePassXC-AutoUnlock-Login-Windows#1]
love the script, thanks a lot for the info.

was getting an error after following the readme. Error: Unable to retrieve the password!

was able to fix by adding a generic credential instead of windows credential.

readme should be changed to state 

Step 2: Add a New Windows Credential

   1. Navigate to Windows Credentials:
        In the Credential Manager window, click on "Windows Credentials."

    2. Add a New Credential:
        Click on the "Add a generic credential" link.

**Comment by PBujakiewicz** [comment]
Yes, you're right. I have already made the correction. Thank you for pointing out the mistake.
